---
- name: Install WordPress stack
  hosts: webservers
  become: yes
  roles:
    - apache
    #- mysql
    - php
    - wordpress
  handlers:
  - name: restart mariadb
    service:
      name: mariadb
      state: restarted
  
  - name: restart apache
    service:
      name: apache2
      state: restarted
