- name: Install PHP and extensions
  apt:
    name: 
      - php{{ php_version }}
      - php{{ php_version }}-fpm
      - php{{ php_version }}-mysql
      - php{{ php_version }}-curl
      - php{{ php_version }}-gd
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-xml
      - php{{ php_version }}-xmlrpc
      - php{{ php_version }}-soap
      - php{{ php_version }}-intl
      - php{{ php_version }}-zip
    state: present
  notify: restart apache
